/**
 * This file is auto-generated using abi-gen. Don't edit directly.
 * Templates can be found at https://github.com/0xProject/0x.js/tree/development/packages/abi-gen-templates.
 */
import { TxData } from '@0xproject/types';
import { BigNumber } from '@0xproject/utils';
import * as Web3 from 'web3';
import { BaseContract } from './base_contract';
export declare class WyvernExchangeContract extends BaseContract {
    INVERSE_BASIS_POINT: {
        sendTransactionAsync(txData?: TxData): Promise<string>;
        estimateGasAsync(txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(): string;
    };
    approveOrder: {
        sendTransactionAsync(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, orderbookInclusionDesired_1: boolean, txData?: TxData): Promise<string>;
        estimateGasAsync(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, orderbookInclusionDesired_1: boolean, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, orderbookInclusionDesired_1: boolean): string;
    };
    approvedOrders: {
        sendTransactionAsync(index_0_0: string, txData?: TxData): Promise<string>;
        estimateGasAsync(index_0_0: string, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(index_0_0: string): string;
    };
    atomicMatch: {
        sendTransactionAsync(buy_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, buySig_1: {
            v: number | BigNumber;
            r: string;
            s: string;
        }, sell_2: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sellSig_3: {
            v: number | BigNumber;
            r: string;
            s: string;
        }, metadata_4: string, txData?: TxData): Promise<string>;
        estimateGasAsync(buy_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, buySig_1: {
            v: number | BigNumber;
            r: string;
            s: string;
        }, sell_2: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sellSig_3: {
            v: number | BigNumber;
            r: string;
            s: string;
        }, metadata_4: string, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(buy_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, buySig_1: {
            v: number | BigNumber;
            r: string;
            s: string;
        }, sell_2: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sellSig_3: {
            v: number | BigNumber;
            r: string;
            s: string;
        }, metadata_4: string): string;
    };
    calculateCurrentPrice: {
        sendTransactionAsync(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, txData?: TxData): Promise<string>;
        estimateGasAsync(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }): string;
    };
    calculateFinalPrice: {
        sendTransactionAsync(side_0: number | BigNumber, saleKind_1: number | BigNumber, basePrice_2: BigNumber, extra_3: BigNumber, listingTime_4: BigNumber, expirationTime_5: BigNumber, txData?: TxData): Promise<string>;
        estimateGasAsync(side_0: number | BigNumber, saleKind_1: number | BigNumber, basePrice_2: BigNumber, extra_3: BigNumber, listingTime_4: BigNumber, expirationTime_5: BigNumber, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(side_0: number | BigNumber, saleKind_1: number | BigNumber, basePrice_2: BigNumber, extra_3: BigNumber, listingTime_4: BigNumber, expirationTime_5: BigNumber): string;
    };
    calculateMatchPrice: {
        sendTransactionAsync(buy_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sell_1: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, txData?: TxData): Promise<string>;
        estimateGasAsync(buy_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sell_1: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(buy_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sell_1: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }): string;
    };
    cancelOrder: {
        sendTransactionAsync(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sig_1: {
            v: number | BigNumber;
            r: string;
            s: string;
        }, txData?: TxData): Promise<string>;
        estimateGasAsync(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sig_1: {
            v: number | BigNumber;
            r: string;
            s: string;
        }, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sig_1: {
            v: number | BigNumber;
            r: string;
            s: string;
        }): string;
    };
    cancelledOrFinalized: {
        sendTransactionAsync(index_0_0: string, txData?: TxData): Promise<string>;
        estimateGasAsync(index_0_0: string, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(index_0_0: string): string;
    };
    changeDevWalletAddress: {
        sendTransactionAsync(newDevWalletAddress_0: string, txData?: TxData): Promise<string>;
        estimateGasAsync(newDevWalletAddress_0: string, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(newDevWalletAddress_0: string): string;
    };
    changeMinimumMakerProtocolFee: {
        sendTransactionAsync(newMinimumMakerProtocolFee_0: BigNumber, txData?: TxData): Promise<string>;
        estimateGasAsync(newMinimumMakerProtocolFee_0: BigNumber, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(newMinimumMakerProtocolFee_0: BigNumber): string;
    };
    changeMinimumTakerProtocolFee: {
        sendTransactionAsync(newMinimumTakerProtocolFee_0: BigNumber, txData?: TxData): Promise<string>;
        estimateGasAsync(newMinimumTakerProtocolFee_0: BigNumber, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(newMinimumTakerProtocolFee_0: BigNumber): string;
    };
    changeProtocolFeeRecipient: {
        sendTransactionAsync(newProtocolFeeRecipient_0: string, txData?: TxData): Promise<string>;
        estimateGasAsync(newProtocolFeeRecipient_0: string, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(newProtocolFeeRecipient_0: string): string;
    };
    codename: {
        sendTransactionAsync(txData?: TxData): Promise<string>;
        estimateGasAsync(txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(): string;
    };
    devWallet: {
        sendTransactionAsync(txData?: TxData): Promise<string>;
        estimateGasAsync(txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(): string;
    };
    exchangeToken: {
        sendTransactionAsync(txData?: TxData): Promise<string>;
        estimateGasAsync(txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(): string;
    };
    guardedArrayReplace: {
        sendTransactionAsync(array_0: string, desired_1: string, mask_2: string, txData?: TxData): Promise<string>;
        estimateGasAsync(array_0: string, desired_1: string, mask_2: string, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(array_0: string, desired_1: string, mask_2: string): string;
    };
    hashOrder: {
        sendTransactionAsync(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, txData?: TxData): Promise<string>;
        estimateGasAsync(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }): string;
    };
    hashToSign: {
        sendTransactionAsync(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, txData?: TxData): Promise<string>;
        estimateGasAsync(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }): string;
    };
    initialize: {
        sendTransactionAsync(registryAddress_0: string, tokenTransferProxyAddress_1: string, tokenAddress_2: string, protocolFeeAddress_3: string, devWalletAddress_4: string, txData?: TxData): Promise<string>;
        estimateGasAsync(registryAddress_0: string, tokenTransferProxyAddress_1: string, tokenAddress_2: string, protocolFeeAddress_3: string, devWalletAddress_4: string, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(registryAddress_0: string, tokenTransferProxyAddress_1: string, tokenAddress_2: string, protocolFeeAddress_3: string, devWalletAddress_4: string): string;
    };
    minimumMakerProtocolFee: {
        sendTransactionAsync(txData?: TxData): Promise<string>;
        estimateGasAsync(txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(): string;
    };
    minimumTakerProtocolFee: {
        sendTransactionAsync(txData?: TxData): Promise<string>;
        estimateGasAsync(txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(): string;
    };
    name: {
        sendTransactionAsync(txData?: TxData): Promise<string>;
        estimateGasAsync(txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(): string;
    };
    orderCalldataCanMatch: {
        sendTransactionAsync(buyCalldata_0: string, buyReplacementPattern_1: string, sellCalldata_2: string, sellReplacementPattern_3: string, txData?: TxData): Promise<string>;
        estimateGasAsync(buyCalldata_0: string, buyReplacementPattern_1: string, sellCalldata_2: string, sellReplacementPattern_3: string, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(buyCalldata_0: string, buyReplacementPattern_1: string, sellCalldata_2: string, sellReplacementPattern_3: string): string;
    };
    ordersCanMatch: {
        sendTransactionAsync(buy_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sell_1: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, txData?: TxData): Promise<string>;
        estimateGasAsync(buy_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sell_1: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(buy_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sell_1: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }): string;
    };
    owner: {
        sendTransactionAsync(txData?: TxData): Promise<string>;
        estimateGasAsync(txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(): string;
    };
    protocolFeeRecipient: {
        sendTransactionAsync(txData?: TxData): Promise<string>;
        estimateGasAsync(txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(): string;
    };
    registry: {
        sendTransactionAsync(txData?: TxData): Promise<string>;
        estimateGasAsync(txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(): string;
    };
    renounceOwnership: {
        sendTransactionAsync(txData?: TxData): Promise<string>;
        estimateGasAsync(txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(): string;
    };
    staticCall: {
        sendTransactionAsync(target_0: string, calldatas_1: string, extradata_2: string, txData?: TxData): Promise<string>;
        estimateGasAsync(target_0: string, calldatas_1: string, extradata_2: string, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(target_0: string, calldatas_1: string, extradata_2: string): string;
    };
    testCopy: {
        sendTransactionAsync(arrToCopy_0: string, txData?: TxData): Promise<string>;
        estimateGasAsync(arrToCopy_0: string, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(arrToCopy_0: string): string;
    };
    testCopyAddress: {
        sendTransactionAsync(addr_0: string, txData?: TxData): Promise<string>;
        estimateGasAsync(addr_0: string, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(addr_0: string): string;
    };
    tokenTransferProxy: {
        sendTransactionAsync(txData?: TxData): Promise<string>;
        estimateGasAsync(txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(): string;
    };
    transferOwnership: {
        sendTransactionAsync(newOwner_0: string, txData?: TxData): Promise<string>;
        estimateGasAsync(newOwner_0: string, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(newOwner_0: string): string;
    };
    validateOrder: {
        sendTransactionAsync(hash_0: string, order_1: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sig_2: {
            v: number | BigNumber;
            r: string;
            s: string;
        }, txData?: TxData): Promise<string>;
        estimateGasAsync(hash_0: string, order_1: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sig_2: {
            v: number | BigNumber;
            r: string;
            s: string;
        }, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(hash_0: string, order_1: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, sig_2: {
            v: number | BigNumber;
            r: string;
            s: string;
        }): string;
    };
    validateOrderParameters: {
        sendTransactionAsync(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, txData?: TxData): Promise<string>;
        estimateGasAsync(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }, txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(order_0: {
            exchange: string;
            maker: string;
            taker: string;
            makerRelayerFee: BigNumber;
            takerRelayerFee: BigNumber;
            makerProtocolFee: BigNumber;
            takerProtocolFee: BigNumber;
            feeRecipient: string;
            feeMethod: number | BigNumber;
            side: number | BigNumber;
            saleKind: number | BigNumber;
            target: string;
            howToCall: number | BigNumber;
            calldatas: string;
            replacementPattern: string;
            staticTarget: string;
            staticExtradata: string;
            paymentToken: string;
            basePrice: BigNumber;
            extra: BigNumber;
            listingTime: BigNumber;
            expirationTime: BigNumber;
            salt: BigNumber;
            dataType: string;
            data: string;
        }): string;
    };
    version: {
        sendTransactionAsync(txData?: TxData): Promise<string>;
        estimateGasAsync(txData?: TxData): Promise<number>;
        getABIEncodedTransactionData(): string;
    };
    constructor(web3ContractInstance: Web3.ContractInstance, defaults: Partial<TxData>);
}
